# Set theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-include-cache

# Site settings
url: ''
baseurl: ''
title: 'Queen City Composers Collective'
description: 'The website of QC3: the Queen City Composers Collective'
permalink: pretty
email: "qc3@example.com"
# logo: ""

# Pagination
paginate: 5
paginate_path: blog/page:num

# Content
stylesheet_serve_path: "/css" # <link rel="stylesheet" href="{{ site.stylesheet_serve_path }}"
image_serve_path: "/images" # <img src="{{ site.image_serve_path }}/img.jpg">
js_serve_path: "/js"

# Collections
collections:
  projects:
    title: Projects
    output: false
    description: "Past projects by QC3"

  members:
    title: Members
    output: false
    description: "The fabulous members of QC3"
    feature_text: |
      This is the feature text for Members collection

  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Defaults
defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
