source "https://rubygems.org"

gem "jekyll", "~> 4.0"
gem "jekyll-mentions", "~> 1.2"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-seo-tag", "~> 2.3"
gem "jekyll-redirect-from", "~> 0.12"
gem "jekyll-feed", "~> 0.9"
gem "jekyll-include-cache"
gem "jekyll-sitemap"
